/*
    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
    SOFTWARE.
*/

/**
    @file
    @brief AVR Toolbox: Control servo motors. Motors constants.
    @author Sergei Ivanov <nsndrz@hotmail.org>
    @copyright The MIT License (MIT)

    Defined characteristics of several common servo motors.
*/

#ifndef __ATB_SERVO_MOTORS
#define __ATB_SERVO_MOTORS

    #define ATB_SERVO_MG90S_PULSE_MIN   1
    #define ATB_SERVO_MG90S_PULSE_MAX   2
    #define ATB_SERVO_MG90S_ANGLE_MAX   180
    #define ATB_SERVO_MG90S_PULSE_PRIOD 20

#endif /* __ATB_SERVO_MOTORS */
